package cn.cheney.xrouter.constant;

public interface GenerateFileConstant {

    String ROUTER_PACKAGE_NAME = "cn.cheney.xrouter";

    String MODULE_FILE_PREFIX = "XRouterModule_";

    String PARAM_FILE_PREFIX = "XRouterXParam_";

    String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY XROUTER.";

}
