package cn.cheney.xrouter.constant;

public interface GenerateFileConstant {

    String MODULE_FILE_PREFIX = "XRoute$$Module$$";

    String PARAM_FILE_PREFIX = "XRoute$$XParam$$";

    String MODULE_CLASS_PREFIX = "cn.cheney.xrouter." + MODULE_FILE_PREFIX;

    String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY XROUTER.";

}
