package cn.cheney.xrouter.constant;

import java.io.File;

public interface GenerateFileConstant {

    /**
     * 生成代码的包名
     */
    String ROUTER_PACKAGE_NAME = "cn.cheney.xrouter";

    String MODULE_FILE_PREFIX = "XRouterModule_";

    String PARAM_FILE_PREFIX = "XRouterXParam_";

    String INTERCEPTOR_FILE_PREFIX = "XRouterInterceptor_";

    String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY XROUTER.";

    /**
     * 路由的包名文件路径 cn/cheney/xrouter
     */
    String ROUTER_MODULE_CLASS_DIR = ROUTER_PACKAGE_NAME.replace('.', File.separatorChar);

    /**
     * cn.cheney.xrouter.XRouterModule_
     */
    String MODULE_CLASS_PREFIX = ROUTER_PACKAGE_NAME + "." + MODULE_FILE_PREFIX;

    /**
     * cn.cheney.xrouter.XRouterInterceptor_
     */
    String INTERCEPTOR_CLASS_PREFIX = ROUTER_PACKAGE_NAME + "." + INTERCEPTOR_FILE_PREFIX;

    /**
     * cn.cheney.xrouter.XRouterModule_Loader
     */
    String ALL_ROUTER_LOAD_CLASS = ROUTER_PACKAGE_NAME + "." + MODULE_FILE_PREFIX + "Loader";
    /**
     * cn.cheney.xrouter.XRouterInterceptor_Loader
     */
    String ALL_INTERCEPTOR_LOAD_CLASS = ROUTER_PACKAGE_NAME + "." + INTERCEPTOR_CLASS_PREFIX + "Loader";

}
